name = "slctrips-saas"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "slctrips-saas-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "slctrips-saas-staging"
vars = { ENVIRONMENT = "staging" }

# D1 Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "slctrips-prod"
database_id = "your_d1_database_id"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "slctrips-staging"
database_id = "your_d1_database_id_staging"

# R2 Storage
[[env.production.r2_buckets]]
binding = "ASSETS"
bucket_name = "slctrips-assets-prod"

[[env.staging.r2_buckets]]
binding = "ASSETS"
bucket_name = "slctrips-assets-staging"

# KV Namespaces for caching
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id_staging"

# Environment variables
[env.production.vars]
SUPABASE_URL = "your_supabase_url"
SUPABASE_ANON_KEY = "your_supabase_anon_key"
NOTION_API_KEY = "your_notion_api_key"
NOTION_DATABASE_ID = "your_notion_database_id"
OPENAI_API_KEY = "your_openai_api_key"

[env.staging.vars]
SUPABASE_URL = "your_supabase_url_staging"
SUPABASE_ANON_KEY = "your_supabase_anon_key_staging"
NOTION_API_KEY = "your_notion_api_key"
NOTION_DATABASE_ID = "your_notion_database_id"
OPENAI_API_KEY = "your_openai_api_key"

# Triggers
[triggers]
crons = [
  "0 0 * * *", # Daily at midnight
  "0 */6 * * *" # Every 6 hours
]

# Routes
[env.production.routes]
pattern = "api.slctrips.com/*"
zone_name = "slctrips.com"

[env.staging.routes]
pattern = "staging-api.slctrips.com/*"
zone_name = "slctrips.com" 